DOMAIN = "movara"

CONF_BASE_URL = "base_url"
CONF_EMAIL = "email"
CONF_PASSWORD = "password"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_ACTIVE_SCAN_INTERVAL = "active_scan_interval"
CONF_ACTIVE_HOLD_SECONDS = "active_hold_seconds"

DEFAULT_SCAN_INTERVAL = 30
DEFAULT_ACTIVE_SCAN_INTERVAL = 5
DEFAULT_ACTIVE_HOLD_SECONDS = 120
